---
title: "Taxa_heatmap"
author: "HS"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## library
```{r}
library(tidyverse)
library(ComplexHeatmap)
```

## laod data and setting 
```{r}
load("output/Ancom_rsl_g_YYBB.Rdata")
load("output/Ancom_rsl.Rdata")
load("output/FT_rarefied_w_taxa_glom.Rdata")
ft_glom_df <- data.table::rbindlist(ft_glom, use.names = T, fill = T, idcol = "taxa.glom")
load("output/Mapping_MS_Urban.Rdata")
Mapping_work <- Mapping_MS_Urban %>% mutate(Urban = ifelse(Ethnicity=="SANEMA", "Low", ifelse(Village=="Fiyakwanha", "Low", ifelse(SampleGroup=="Visitors", "High", "Medium"))) %>% factor(levels = c("Low", "Medium", "High")), Age_num = as.numeric(Age), Age_num = ifelse(is.na(Age_num), as.numeric(gsub(pattern = "_months", replacement = "", Age, ignore.case = T))/12, Age_num), Age_grp1 = ifelse(Age_num>=18, "Adults", "Children"))
Mapping_work$Age_num[Mapping_work$Age=="4_Days"] <- 0
Mapping_work$Age_num[Mapping_work$Age=="1_day"] <- 0
Mapping_work$Age_grp1[Mapping_work$Age_num==0] <- "Children"
Mapping_work2 <- Mapping_work %>% mutate(Age_grp2 = case_when(Age_num<=3 ~ "Age_0-3", Age_num<=8 ~ "Age_3-8", Age_num<=18 ~ "Age_8-18", T ~ "Adults") %>% factor(levels = c("Age_0-3", "Age_3-8", "Age_8-18", "Adults")))
nc = 2

Urban_color <- c("#66c2a5", "#fc8d62", "#8da0cb")
names(Urban_color) <- c("Low", "Medium", "High")

Blasto_color = c("#4EB14B","#E61225")
names(Blasto_color) = c("Negative", "Positive")
```

## Ancom
```{r functions, eval=FALSE}
source("ANCOM_updated_code_06_06_2020.R")

ancom_wrap <- function(featuretable, metadata, ...){
    ft <- featuretable # feature table is in a format that a column of taxa with additional columns of counts from each samples
    mt <- metadata
    
    # filter feature table to remove features that appeared in less than 10% of samples
    sample_names <- colnames(ft)[-1]
    n_samples <- length(sample_names)
    ft_flt <- ft[rowSums(ft[, -1]>0)>=0.1*n_samples, ]
    
    ## create ancom format feature table
    ft_ancom <- ft_flt[, -1] %>% t() %>% as.data.frame() %>% rownames_to_column(var = "Sample.ID")
    colnames(ft_ancom) <- c("Sample.ID", ft_flt$Taxa) %>% make.names()
    
    
    # filter metadata
    mt_ancom <- mt %>% filter(SampleID %in% ft_ancom$Sample.ID) %>% rename(Sample.ID = SampleID)
    
    ancom_mod <- ANCOM.main(OTUdat = ft_ancom, Vardat = mt_ancom, ...)
    return(ancom_mod)
    
}
```

## per year, per sites, age_num
```{r}
Ancom_mf_lst_2 <- Mapping_work2 %>% filter(SampleGroup=="Villagers", Body_Site %in% BodySites) %>% group_by(Year, Body_Site) %>% group_split()

Ancom_rsl_2 <- parallel::mclapply(Ancom_mf_lst_2, function(x){
    list(x[1, c("Year", "Body_Site")], ancom_wrap(ft_glom$Genus %>% select(Taxa, any_of(x$SampleID)), x, adjusted = T, main.var = "Urban", adj.formula = "Gender+Age_num", repeat.var = NULL, longitudinal = F, random.formula = NULL, multcorr = 2, sig = 0.05, prev.cut = 1))
    }, mc.cores = nc)
```

### prepare data
```{r}
Ancom_rsl_2_tbl <- lapply(Ancom_rsl_2, function(x){x[[2]]$W.taxa %>% mutate(Year = as.character(x[[1]][1,1]), Body_Site = as.character(x[[1]][1,2]))}) %>% do.call("rbind", .) %>% 
  filter(!grepl(pattern = "D_1_\\.D", otu.names))

Yrs <- c("2015", "2016")
BodySites <- c("Feces", "Mouth", "Nose", "Right_Arm", "Right_Hand")

while(F){
  sig_cutoff <- integer()
  for (YY in Yrs){
    # YY = 2015
    for (BB in BodySites){
      # BB = "Feces"
      ## metadata
      Mf <- Mapping_work2 %>% filter(Year==YY, Body_Site==BB, SampleGroup=="Villagers")
      ## Ancom results and catogrize the species according to W/effect size
      AR <- Ancom_rsl_2_tbl %>% filter(Year==YY, Body_Site==BB) %>% mutate(otu.names = as.character(otu.names)) %>% arrange(desc(W_stat))
      ### check the distribution of W-stats, 
      p <- ggplot(AR, aes(x = W_stat)) +
        geom_histogram(aes(y = ..density..), bins = 20) +
        geom_density() +
        geom_vline(xintercept = nrow(AR)*seq(0.6, 0.9, 0.1)) + 
        theme_bw() +
        labs(title = paste(YY, BB, sep = "-"))
      print(p)
      
      table(AR$ES)
      #sig_cutoff[paste(YY, BB, sep = "-")] <- readline(prompt = "Above which cut off deemed as significant? LT0.6(1), LT0.7(2), LT0.8(3), LT0.9(4)")
    }
  }
}

sig_cutoff = c(1, 2, 2, 3, 3, 1, 3, 1, 3, 3)
names(sig_cutoff) = c("2015-Feces", "2015-Mouth", "2015-Nose", "2015-Right_Arm", "2015-Right_Hand", "2016-Feces", "2016-Mouth", "2016-Nose", "2016-Right_Arm", "2016-Right_Hand")

fts_mt <- parallel::mclapply(cross2(BodySites, Yrs), function(x){
    list(Mf = Mapping_work2 %>% filter(Year==x[[2]], Body_Site==x[[1]], SampleGroup=="Villagers"),
         AR = Ancom_rsl_2_tbl %>% filter(Year==x[[2]], Body_Site==x[[1]]) %>% mutate(otu.names = as.character(otu.names)) %>% arrange(desc(W_stat)))},
    mc.cores = nc)

fts <- parallel::mclapply(fts_mt, function(x){ft_glom$Genus %>% 
    select(Taxa:Genus, any_of(x$Mf$SampleID)) %>% 
    mutate(Taxa = make.names(Taxa)) %>%
    filter(Taxa %in% x$AR$otu.names)}, mc.cores = nc)

lrs_b_grp <- list()
for (ss in seq_along(fts)){
    # ss = 3
    # prepare datasets
    ft_t <- fts[[ss]]
    Mf <- fts_mt[[ss]][["Mf"]] %>% filter(SampleID %in% colnames(ft_t))
    YY = Mf$Year[1]
    BB = Mf$Body_Site[1]
    
    # relative abundance
    ft_t_rel_ab <- ft_t %>% mutate(across(starts_with("X"), ~ .x/10000))
        
    # rel abundance in log scale
    ft_t_rel_ab_log10 <- ft_t_rel_ab %>% mutate(across(starts_with("X"), ~ ifelse(.x == 0, log10(0.0001), log10(.x))))
    
    # calcualate the log ratio of a taxa between medium and low exposure level
    #lr_b_grp <- split(ft_t_rel_ab_log10, ft_t_rel_ab_log10$Taxa) %>% lapply(., function(x){10^((t(x[, -1]) %>% merge(., Mf, by.x = 0, by.y = 1) %>% lm(V1 ~ Urban + Age_grp2 + Gender, data = .))$coefficient[2]) %>% log2() }) %>% unlist(use.names = T)
    #names(lr_b_grp) <- names(lr_b_grp) %>% gsub(pattern = "\\.UrbanMedium", replacement = "", x = .)
    #lrs_b_grp[[ss]] <- lr_b_grp
  
    coef_p_l = split(ft_t_rel_ab_log10, ft_t_rel_ab_log10$Taxa) %>% lapply(., function(x){coefd = (t(x[, -1]) %>% 
                                                                                      merge(., Mf, by.x = 0, by.y = 1) %>% 
                                                                                      lm(V1 ~ Urban + Age_grp2 + Gender, data = .) %>% 
                                                                                      summary())$coefficients
                                                                              coefd[which(str_detect(rownames(coefd), "Urban")),c("Estimate", "Pr(>|t|)")]
                                                                              })
    #coef_and_p = data.frame(matrix(unlist(coef_p_l), nrow = length(coef_p_l), byrow = T))
    coef_and_p = do.call(rbind.data.frame, coef_p_l)
    names(coef_and_p) = c("coef","pvalue")
    rownames(coef_and_p) = names(coef_p_l)
    coef_and_p$padj = p.adjust(coef_and_p$pvalue, method = "BH")
    coef_and_p$LR = log2(10^coef_and_p$coef)
    lrs_b_grp[[ss]] <- coef_and_p
}

```

### heatmap
```{r}
for (ss in seq_along(fts)){
    # ss = 3
    # prepare datasets
    ft_t <- fts[[ss]]
    Mf <- fts_mt[[ss]][["Mf"]] %>% filter(SampleID %in% colnames(ft_t))
    YY = Mf$Year[1]
    BB = Mf$Body_Site[1]
    lr_b_grp = lrs_b_grp[[ss]]
    AR_g <- fts_mt[[ss]]$AR
    # defining taxa that changed and unchanged based on sig_cutoff
    ind = paste(YY, BB, sep = "-")
    ES_cutoff <- paste0("detected_",seq(0.6, 0.9, 0.1)[sig_cutoff[ind]])
    
    # relative abundance
    ft_t_rel_ab <- ft_t %>% mutate(across(starts_with("X"), ~ .x/10000))
    
    # rel abundance in log scale
    ft_t_rel_ab_log10 <- ft_t_rel_ab %>% mutate(across(starts_with("X"), ~ ifelse(.x == 0, log10(0.0001), log10(.x))))
    
    # heatmap of significantly changed features
    ## dataframe for the column annotation
    df_col <- Mf %>% select(SampleID, Age_grp2, Urban, Gender) %>% mutate(Urban =  as.character(Urban)) %>% arrange(Urban, Age_grp2) %>% column_to_rownames(var = "SampleID")
    ## dataframe for the row(taxa) annotation, only significantly modified genera included
    #df_row <- data.frame(LR = lr_b_grp[AR_g[which(AR_g[ES_cutoff]==TRUE & !str_detect(AR_g$otu.names, pattern = "Mitochondria|Chloroplast")), "otu.names"]])
    
    taxa_stat = merge(lr_b_grp, AR_g, by.x = 0, by.y = 1)
    df_row = taxa_stat[which(taxa_stat[,ES_cutoff]==TRUE),]
    df_row = df_row %>% filter(!str_detect(Row.names, pattern = "Mitochondria|Chloroplast"), padj < 0.1) %>% 
      mutate(Sign = case_when(LR <= -2 ~ "--",
                              LR < 0 ~ "-",
                              LR == 0 ~ "",
                              LR < 2 ~ "+",
                              LR >= 2 ~ "++"),
             LR_abs = abs(LR)) %>% column_to_rownames("Row.names")
    if(nrow(df_row) > 40){df_row = df_row %>% arrange(desc(LR_abs)) %>% top_n(n = 40, wt = LR_abs)}
 
    df_row_name_label = structure(gsub("D_\\d_", "", rownames(df_row)), names = rownames(df_row))
    ## this is used to create the legend
    LR_sig_range <- df_row$LR %>% range
    
    ## data matrix for the heatmap
    mat_dat <- ft_t_rel_ab_log10 %>% select(Taxa, starts_with("X")) %>% column_to_rownames(var = "Taxa") %>% as.matrix %>% .[rownames(df_row), rownames(df_col)]
    ### annotation components
    mat_col_fun = circlize::colorRamp2(c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), c("#253494","#2c7fb8","#41b6c4", "#7fcdbb", "#c7e9b4", "#ffffcc"))
    #genus_text_col = ifelse(df_row>0, "#fc8d62", "#66c2a5")
    
    column_ha = HeatmapAnnotation(df = df_col %>% select(Urban, Age_grp2), 
                                  col = list(Urban = Urban_color, 
                                             Age_grp2 = c("Age_0-3" = "#f1eef6", "Age_3-8" = "#bdc9e1","Age_8-18" = "#74a9cf", "Adults" = "#0570b0")), 
                                  simple_anno_size = unit(3, "mm"), 
                                  annotation_label = c("Exposure", "Age"), 
                                  annotation_name_gp = gpar(fontsize = 7,fontface = "bold"), 
                                  annotation_name_side = "left", 
                                  annotation_legend_param = list(Urban = list(labels_gp = gpar(fontsize = 7), 
                                                                              title_gp = gpar(fontsize = 8, fontface = "bold")), 
                                                                 Age_grp2 = list(labels_gp = gpar(fontsize = 7), 
                                                                                 title_gp = gpar(fontsize = 8, fontface = "bold"))))
    
#    row_ha = rowAnnotation(df = df_row, 
#                           col = list(LR = circlize::colorRamp2(c(-max(abs(LR_sig_range)), 0, max(abs(LR_sig_range))), c("#1b9e77", "white", "#d95f02"))), 
#                           gp = gpar(col = "black", lwd = 0.3), 
#                           annotation_name_gp = gpar(fontsize = 7), 
#                           annotation_name_side = "top", 
#                           annotation_legend_param = list(LR = list(labels_gp = gpar(fontsize = 7), 
#                                                                    title_gp = gpar(fontsize = 8, fontface = "bold", angle = 0))))
    
    row_ha = rowAnnotation(foo = anno_text(df_row$Sign, location = 0, rot = 0, just = "left"), 
                           gp = gpar(col = "black", lwd = 0.3), 
                           annotation_name_gp = gpar(fontsize = 7), 
                           annotation_name_side = "top")

    p <- Heatmap(mat_dat, 
                 col = mat_col_fun, 
                 name = "Relative Abundance", 
                 heatmap_legend_param = list(at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), 
                                             labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"), 
                                             labels_gp = gpar(fontsize = 7), 
                                             title_gp = gpar(fontsize = 8, fontface = "bold")),
                 cluster_columns = F, show_column_names = F,
                 column_order = rownames(df_col),
                 column_title_gp = gpar(fontsize = 7, fontface = "bold"),
                 column_split = df_col$Urban,
                 #row_names_gp = gpar(col = genus_text_col, fontsize = 7),
                 row_names_gp = gpar(fontsize = 8), 
                 row_labels = df_row_name_label[rownames(df_row)],
                 row_dend_width = unit(15, "mm"),
                 row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
                 top_annotation = column_ha,
                 right_annotation = row_ha,
                 height = unit(8, "mm")*dim(mat_dat)[1],
                 width = unit(0.8, "mm")*dim(mat_dat)[2], 
    )
    p1 <- draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
    pdf(file = paste0("output/figures/Ancom_heatmap_sig_log_rel_ab_", BB, "_", YY, "_pvalue_filtered.pdf"), width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4, useDingbats = F)
    draw(p1)
    dev.off()
    
    p_genus_order = rownames(df_row)[row_order(draw(p))]
    p1_dat <- data.frame(Taxa = p_genus_order, stringsAsFactors = F) %>% separate(Taxa, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus"), sep = "\\.D_\\d_", remove = F) %>% mutate(Domain = gsub(x = Domain, pattern = "D_0_", replacement = ""))
    p1_dat$LR <- df_row$LR
    p1_dat$Flag <- p1_dat$LR>0
    p1_dat$No = rownames(p1_dat)
    p1_dat$BodySite = BB
    p1_dat$Year = YY
    write.table(p1_dat, file = paste0("output/figures/Ancom_sig_log_rel_ab_", BB, "_", YY, "_genera.txt"), sep = "\t", row.names = F, quote = F)
}
```

## per year, per sites, age_gpr2
```{r}
Ancom_mf_lst_2 <- Mapping_work2 %>% filter(SampleGroup=="Villagers", Body_Site %in% BodySites) %>% group_by(Year, Body_Site) %>% group_split()

Ancom_rsl_2_age_grp2 <- parallel::mclapply(Ancom_mf_lst_2, function(x){
    list(x[1, c("Year", "Body_Site")], ancom_wrap(ft_glom$Genus %>% select(Taxa, any_of(x$SampleID)), x, adjusted = T, main.var = "Urban", adj.formula = "Gender+Age_grp2", repeat.var = NULL, longitudinal = F, random.formula = NULL, multcorr = 2, sig = 0.05, prev.cut = 1))
    }, mc.cores = 2)

save(Ancom_rsl_2_age_grp2, file = "output/Ancom_rsl_g_YYBB_Age_grp2.Rdata")
load("output/Ancom_rsl_g_YYBB_Age_grp2.Rdata")
```

### data prep
```{r}
Ancom_rsl_2_tbl_grp2 <- lapply(Ancom_rsl_2_age_grp2, function(x){x[[2]]$W.taxa %>% mutate(Year = as.character(x[[1]][1,1]), Body_Site = as.character(x[[1]][1,2]))}) %>% do.call("rbind", .) %>% 
  filter(!grepl(pattern = "D_1_\\.D", otu.names))

Yrs <- c("2015", "2016")
BodySites <- c("Feces", "Mouth", "Nose", "Right_Arm", "Right_Hand")

while(F){
  sig_cutoff <- integer()
  for (YY in Yrs){
    # YY = 2015
    for (BB in BodySites){
      # BB = "Feces"
      ## metadata
      Mf <- Mapping_work2 %>% filter(Year==YY, Body_Site==BB, SampleGroup=="Villagers")
      ## Ancom results and catogrize the species according to W/effect size
      AR <- Ancom_rsl_2_tbl_grp2 %>% filter(Year==YY, Body_Site==BB) %>% mutate(otu.names = as.character(otu.names)) %>% arrange(desc(W_stat))
      ### check the distribution of W-stats, 
      p <- ggplot(AR, aes(x = W_stat)) +
        geom_histogram(aes(y = ..density..), bins = 20) +
        geom_density() +
        geom_vline(xintercept = nrow(AR)*seq(0.6, 0.9, 0.1)) + 
        theme_bw() +
        labs(title = paste(YY, BB, sep = "-"))
      print(p)
      
      table(AR$ES)
      #sig_cutoff[paste(YY, BB, sep = "-")] <- readline(prompt = "Above which cut off deemed as significant? LT0.6(1), LT0.7(2), LT0.8(3), LT0.9(4)")
    }
  }
}

sig_cutoff = c(1, 2, 3, 4, 4, 1, 2, 1, 3, 3)
names(sig_cutoff) = c("2015-Feces", "2015-Mouth", "2015-Nose", "2015-Right_Arm", "2015-Right_Hand", "2016-Feces", "2016-Mouth", "2016-Nose", "2016-Right_Arm", "2016-Right_Hand")

fts_mt <- parallel::mclapply(cross2(BodySites, Yrs), function(x){
    list(Mf = Mapping_work2 %>% filter(Year==x[[2]], Body_Site==x[[1]], SampleGroup=="Villagers"),
         AR = Ancom_rsl_2_tbl_grp2 %>% filter(Year==x[[2]], Body_Site==x[[1]]) %>% mutate(otu.names = as.character(otu.names)) %>% arrange(desc(W_stat)))},
    mc.cores = nc)

fts <- parallel::mclapply(fts_mt, function(x){ft_glom$Genus %>% 
    select(Taxa:Genus, any_of(x$Mf$SampleID)) %>% 
    mutate(Taxa = make.names(Taxa)) %>%
    filter(Taxa %in% x$AR$otu.names)}, mc.cores = nc)

lrs_b_grp <- list()
for (ss in seq_along(fts)){
    # ss = 3
    # prepare datasets
    ft_t <- fts[[ss]]
    Mf <- fts_mt[[ss]][["Mf"]] %>% filter(SampleID %in% colnames(ft_t))
    YY = Mf$Year[1]
    BB = Mf$Body_Site[1]
    
    # relative abundance
    ft_t_rel_ab <- ft_t %>% mutate(across(starts_with("X"), ~ .x/10000))
        
    # rel abundance in log scale
    ft_t_rel_ab_log10 <- ft_t_rel_ab %>% mutate(across(starts_with("X"), ~ ifelse(.x == 0, log10(0.0001), log10(.x))))
    
    # calcualate the log ratio of a taxa between medium and low exposure level
    #lr_b_grp <- split(ft_t_rel_ab_log10, ft_t_rel_ab_log10$Taxa) %>% lapply(., function(x){10^((t(x[, -1]) %>% merge(., Mf, by.x = 0, by.y = 1) %>% lm(V1 ~ Urban + Age_grp2 + Gender, data = .))$coefficient[2]) %>% log2() }) %>% unlist(use.names = T)
    #names(lr_b_grp) <- names(lr_b_grp) %>% gsub(pattern = "\\.UrbanMedium", replacement = "", x = .)
    #lrs_b_grp[[ss]] <- lr_b_grp
    coef_p_l = split(ft_t_rel_ab_log10, ft_t_rel_ab_log10$Taxa) %>% lapply(., function(x){coefd = (t(x[, -1]) %>% 
                                                                                      merge(., Mf, by.x = 0, by.y = 1) %>% 
                                                                                      lm(V1 ~ Urban + Age_grp2 + Gender, data = .) %>% 
                                                                                      summary())$coefficients
                                                                              coefd[which(str_detect(rownames(coefd), "Urban")),c("Estimate", "Pr(>|t|)")]
                                                                              })
    #coef_and_p = data.frame(matrix(unlist(coef_p_l), nrow = length(coef_p_l), byrow = T))
    coef_and_p = do.call(rbind.data.frame, coef_p_l)
    names(coef_and_p) = c("coef","pvalue")
    rownames(coef_and_p) = names(coef_p_l)
    coef_and_p$padj = p.adjust(coef_and_p$pvalue, method = "BH")
    coef_and_p$LR = log2(10^coef_and_p$coef)
    lrs_b_grp[[ss]] <- coef_and_p
}
```

### heatmap
```{r}
dat_ind = data.frame(index = seq_along(fts_mt), Year = NA, Bodysite = NA)
for (ss in seq_along(fts_mt)){
  dat_ind[which(dat_ind$index==ss), "Year"] = fts_mt[[ss]]$Mf$Year[1]
  dat_ind[which(dat_ind$index==ss), "Bodysite"] = fts_mt[[ss]]$Mf$Body_Site[1]
}

for (ss in seq_along(fts)){
    ft_t <- fts[[ss]]
    Mf <- fts_mt[[ss]][["Mf"]] %>% filter(SampleID %in% colnames(ft_t))
    YY = Mf$Year[1]
    BB = Mf$Body_Site[1]
    lr_b_grp = lrs_b_grp[[ss]]
    AR_g <- fts_mt[[ss]]$AR
    # defining taxa that changed and unchanged based on sig_cutoff
    ind = paste(YY, BB, sep = "-")
    ES_cutoff <- paste0("detected_",seq(0.6, 0.9, 0.1)[sig_cutoff[ind]])
    
    # relative abundance
    ft_t_rel_ab <- ft_t %>% mutate(across(starts_with("X"), ~ .x/10000))
    
    # rel abundance in log scale
    ft_t_rel_ab_log10 <- ft_t_rel_ab %>% mutate(across(starts_with("X"), ~ ifelse(.x == 0, log10(0.0001), log10(.x))))
    
    # heatmap of significantly changed features
    ## dataframe for the column annotation
    df_col <- Mf %>% select(SampleID, Age_grp2, Urban, Gender) %>% mutate(Urban =  as.character(Urban)) %>% arrange(Urban, Age_grp2) %>% column_to_rownames(var = "SampleID")
    ## dataframe for the row(taxa) annotation, only significantly modified genera included

    taxa_stat = merge(lr_b_grp, AR_g, by.x = 0, by.y = 1)
    df_row = taxa_stat[which(taxa_stat[,ES_cutoff]==TRUE),]
    df_row = df_row %>% filter(!str_detect(Row.names, pattern = "Mitochondria|Chloroplast"), padj < 0.1) %>% 
      mutate(Sign = case_when(LR <= -2 ~ "--",
                              LR < 0 ~ "-",
                              LR == 0 ~ "",
                              LR < 2 ~ "+",
                              LR >= 2 ~ "++"),
             LR_abs = abs(LR)) %>% column_to_rownames("Row.names")
    if(nrow(df_row) > 40){df_row = df_row %>% arrange(desc(LR_abs)) %>% top_n(n = 40, wt = LR_abs)}
    df_row_name_label = structure(gsub("D_\\d_", "", rownames(df_row)), names = rownames(df_row))
    ## this is used to create the legend
    LR_sig_range <- df_row$LR %>% range
    
    ## data matrix for the heatmap
    mat_dat <- ft_t_rel_ab_log10 %>% select(Taxa, starts_with("X")) %>% column_to_rownames(var = "Taxa") %>% as.matrix %>% .[rownames(df_row), rownames(df_col)]
    ### annotation components
    mat_col_fun = circlize::colorRamp2(c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), c("#253494","#2c7fb8","#41b6c4", "#7fcdbb", "#c7e9b4", "#ffffcc"))
    
    if(YY == 2015){
      genus_text_col = ifelse(df_row$LR>0, "black", "black")
    }else{
      ind_2015 =  dat_ind %>% filter(Year==2015, Bodysite==BB) %>% pull(index)
      lr_b_grp_2015 = lrs_b_grp[[ind_2015]]
      ES_cutoff_2015 <- paste0("detected_",seq(0.6, 0.9, 0.1)[sig_cutoff[paste("2015", BB, sep = "-")]])
      AR_g_2015 <- fts_mt[[ind_2015]]$AR
      taxa_stat_2015 = merge(lr_b_grp_2015, AR_g_2015, by.x = 0, by.y = 1)
      df_row_2015 = taxa_stat_2015[which(taxa_stat_2015[,ES_cutoff]==TRUE),]
      df_row_2015 = df_row_2015 %>% filter(!str_detect(Row.names, pattern = "Mitochondria|Chloroplast"), padj < 0.1) %>% column_to_rownames("Row.names")  
      pos = df_row_2015 %>% filter(LR > 0) %>% rownames()
      neg = df_row_2015 %>% filter(LR < 0) %>% rownames()
      df_row = df_row %>% mutate(col = case_when(LR>0 & (rownames(.) %in% pos) ~ "red",
                                        LR<0 & (rownames(.) %in% neg) ~ "red",
                                        TRUE ~ "black"))
      genus_text_col = df_row$col
    }

    column_ha = HeatmapAnnotation(df = df_col %>% select(Urban, Age_grp2), 
                                  col = list(Urban = Urban_color, 
                                             Age_grp2 = c("Age_0-3" = "#f1eef6", "Age_3-8" = "#bdc9e1","Age_8-18" = "#74a9cf", "Adults" = "#0570b0")), 
                                  simple_anno_size = unit(3, "mm"), 
                                  annotation_label = c("Exposure", "Age"), 
                                  annotation_name_gp = gpar(fontsize = 7,fontface = "bold"), 
                                  annotation_name_side = "left", 
                                  annotation_legend_param = list(Urban = list(labels_gp = gpar(fontsize = 7), 
                                                                              title_gp = gpar(fontsize = 8, fontface = "bold")), 
                                                                 Age_grp2 = list(labels_gp = gpar(fontsize = 7), 
                                                                                 title_gp = gpar(fontsize = 8, fontface = "bold"))))
    
    row_ha = rowAnnotation(foo = anno_text(df_row$Sign, location = 0, rot = 0, just = "left"), 
                           gp = gpar(col = "black", lwd = 0.3), 
                           annotation_name_gp = gpar(fontsize = 7), 
                           annotation_name_side = "top")

    p <- Heatmap(mat_dat, 
                 col = mat_col_fun, 
                 name = "Relative Abundance", 
                 heatmap_legend_param = list(at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), 
                                             labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"), 
                                             labels_gp = gpar(fontsize = 7), 
                                             title_gp = gpar(fontsize = 8, fontface = "bold")),
                 cluster_columns = F, show_column_names = F,
                 column_order = rownames(df_col),
                 column_title_gp = gpar(fontsize = 7, fontface = "bold"),
                 column_split = df_col$Urban,
                 row_names_gp = gpar(col = genus_text_col, fontsize = 8),
                 row_labels = df_row_name_label[rownames(df_row)],
                 row_dend_width = unit(15, "mm"),
                 row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
                 top_annotation = column_ha,
                 right_annotation = row_ha,
                 height = unit(8, "mm")*dim(mat_dat)[1],
                 width = unit(0.8, "mm")*dim(mat_dat)[2], 
    )
    p1 <- draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
    pdf(file = paste0("output/figures/Ancom_heatmap_sig_log_rel_ab_by_grp2_", BB, "_", YY, "_pvalue_filtered.pdf"), width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4, useDingbats = F)
    draw(p1)
    dev.off()
    
    p_genus_order = rownames(df_row)[row_order(draw(p))]
    p1_dat <- data.frame(Taxa = p_genus_order, stringsAsFactors = F) %>% separate(Taxa, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus"), sep = "\\.D_\\d_", remove = F) %>% mutate(Domain = gsub(x = Domain, pattern = "D_0_", replacement = ""))
    p1_dat$LR <- df_row$LR
    p1_dat$Flag <- p1_dat$LR>0
    p1_dat$No = rownames(p1_dat)
    p1_dat$BodySite = BB
    p1_dat$Year = YY
    write.table(p1_dat, file = paste0("output/figures/Ancom_sig_log_rel_ab_by_grp2_", BB, "_", YY, "_genera.txt"), sep = "\t", row.names = F, quote = F)
}
```


## compare low between 2015 and 2016
```{r}
Ancom_year = Mapping_work2 %>% filter(SampleGroup=="Villagers", Body_Site %in% BodySites, Urban == "Low") %>% group_by(Body_Site) %>% group_split()

Ancom_rsl_year_low <- parallel::mclapply(Ancom_year, function(x){
    list(x[1, "Body_Site"], ancom_wrap(ft_glom$Genus %>% select(Taxa, any_of(x$SampleID)), x, adjusted = T, main.var = "Year", adj.formula = "Gender+Age_grp2", repeat.var = NULL, longitudinal = F, random.formula = NULL, multcorr = 2, sig = 0.05, prev.cut = 1))
    }, mc.cores = 2)

save(Ancom_rsl_year_low, file = "output/Ancom_rsl_year_g.Rdata")
load("output/Ancom_rsl_year_g.Rdata")
```

### data prep
```{r}
Ancom_rsl_year_low_tbl <- lapply(Ancom_rsl_year_low, function(x){x[[2]]$W.taxa %>% mutate(Body_Site = as.character(x[[1]][1]))}) %>% do.call("rbind", .) %>% 
  filter(!grepl(pattern = "D_1_\\.D", otu.names))

BodySites <- c("Feces", "Mouth", "Nose", "Right_Arm", "Right_Hand")

while(F){
  sig_cutoff <- integer()
  for (BB in BodySites){
      # BB = "Feces"
      ## metadata
      Mf <- Mapping_work2 %>% filter(Body_Site==BB, SampleGroup=="Villagers")
      ## Ancom results and catogrize the species according to W/effect size
      AR <- Ancom_rsl_year_low_tbl %>% filter(Body_Site==BB) %>% mutate(otu.names = as.character(otu.names)) %>% arrange(desc(W_stat))
      ### check the distribution of W-stats, 
      p <- ggplot(AR, aes(x = W_stat)) +
        geom_histogram(aes(y = ..density..), bins = 20) +
        geom_density() +
        geom_vline(xintercept = nrow(AR)*seq(0.6, 0.9, 0.1)) + 
        theme_bw() +
        labs(title = BB)
      print(p)
      
      table(AR$ES)
      #sig_cutoff[BB] <- readline(prompt = "Above which cut off deemed as significant? LT0.6(1), LT0.7(2), LT0.8(3), LT0.9(4)")
  }
}

sig_cutoff = c(1, 1, 1, 1, 1)
names(sig_cutoff) = c("Feces", "Mouth", "Nose", "Right_Arm", "Right_Hand")

fts_mt <- parallel::mclapply(BodySites, function(x){
    list(Mf = Mapping_work2 %>% filter(Body_Site==x, SampleGroup=="Villagers", Urban == "Low"),
         AR = Ancom_rsl_year_low_tbl %>% filter(Body_Site==x) %>% mutate(otu.names = as.character(otu.names)) %>% arrange(desc(W_stat)))},
    mc.cores = nc)

fts <- parallel::mclapply(fts_mt, function(x){ft_glom$Genus %>% 
    select(Taxa:Genus, any_of(x$Mf$SampleID)) %>% 
    mutate(Taxa = make.names(Taxa)) %>%
    filter(Taxa %in% x$AR$otu.names)}, mc.cores = nc)

lrs_b_grp <- list()
for (ss in seq_along(fts)){
    ft_t <- fts[[ss]]
    Mf <- fts_mt[[ss]][["Mf"]] %>% filter(SampleID %in% colnames(ft_t))
    YY = Mf$Year[1]
    BB = Mf$Body_Site[1]

    ft_t_rel_ab <- ft_t %>% mutate(across(starts_with("X"), ~ .x/10000))

    ft_t_rel_ab_log10 <- ft_t_rel_ab %>% mutate(across(starts_with("X"), ~ ifelse(.x == 0, log10(0.0001), log10(.x))))

    #lr_b_grp <- split(ft_t_rel_ab_log10, ft_t_rel_ab_log10$Taxa) %>% lapply(., function(x){10^((t(x[, -1]) %>% merge(., Mf, by.x = 0, by.y = 1) %>% lm(V1 ~ Year + Age_grp2 + Gender, data = .))$coefficient[2]) %>% log2() }) %>% unlist(use.names = T)
    #names(lr_b_grp) <- names(lr_b_grp) %>% gsub(pattern = "\\.Year", replacement = "", x = .)
    #lrs_b_grp[[ss]] <- lr_b_grp
    
    coef_p_l = split(ft_t_rel_ab_log10, ft_t_rel_ab_log10$Taxa) %>% lapply(., function(x){coefd = (t(x[, -1]) %>% 
                                                                                      merge(., Mf, by.x = 0, by.y = 1) %>% 
                                                                                      lm(V1 ~ Year + Age_grp2 + Gender, data = .) %>% 
                                                                                      summary())$coefficients
                                                                              coefd[which(str_detect(rownames(coefd), "Year")),c("Estimate", "Pr(>|t|)")]
                                                                              })
    coef_and_p = do.call(rbind.data.frame, coef_p_l)
    names(coef_and_p) = c("coef","pvalue")
    rownames(coef_and_p) = names(coef_p_l)
    coef_and_p$padj = p.adjust(coef_and_p$pvalue, method = "BH")
    coef_and_p$LR = log2(10^coef_and_p$coef)
    lrs_b_grp[[ss]] <- coef_and_p
    
}
```

### heatmap
```{r}
for (ss in seq_along(fts)){

    ft_t <- fts[[ss]]
    Mf <- fts_mt[[ss]][["Mf"]] %>% filter(SampleID %in% colnames(ft_t))
    YY = Mf$Year[1]
    BB = Mf$Body_Site[1]
    lr_b_grp = lrs_b_grp[[ss]]
    AR_g <- fts_mt[[ss]]$AR
    # defining taxa that changed and unchanged based on sig_cutoff
    ind = BB
    ES_cutoff <- paste0("detected_",seq(0.6, 0.9, 0.1)[sig_cutoff[ind]])
    # relative abundance
    ft_t_rel_ab <- ft_t %>% mutate(across(starts_with("X"), ~ .x/10000))
    # rel abundance in log scale
    ft_t_rel_ab_log10 <- ft_t_rel_ab %>% mutate(across(starts_with("X"), ~ ifelse(.x == 0, log10(0.0001), log10(.x))))
    # heatmap of significantly changed features
    ## dataframe for the column annotation
    df_col <- Mf %>% select(SampleID, Age_grp2, Year) %>% arrange(Year,Age_grp2) %>% column_to_rownames(var = "SampleID")
    ## dataframe for the row(taxa) annotation, only significantly modified genera included
    
    taxa_stat = merge(lr_b_grp, AR_g, by.x = 0, by.y = 1)
    df_row = taxa_stat[which(taxa_stat[,ES_cutoff]==TRUE),]
    df_row = df_row %>% filter(!str_detect(Row.names, pattern = "Mitochondria|Chloroplast"), padj < 0.1) %>% 
      mutate(Sign = case_when(LR <= -2 ~ "--",
                              LR < 0 ~ "-",
                              LR == 0 ~ "",
                              LR < 2 ~ "+",
                              LR >= 2 ~ "++"),
             LR_abs = abs(LR)) %>% column_to_rownames("Row.names")
    if(nrow(df_row) > 40){df_row = df_row %>% arrange(desc(LR_abs)) %>% top_n(n = 40, wt = LR_abs)}
    df_row_name_label = structure(gsub("D_\\d_", "", rownames(df_row)), names = rownames(df_row))
    ## this is used to create the legend
    LR_sig_range <- df_row$LR %>% range
    ## data matrix for the heatmap
    mat_dat <- ft_t_rel_ab_log10 %>% select(Taxa, starts_with("X")) %>% column_to_rownames(var = "Taxa") %>% as.matrix %>% .[rownames(df_row), rownames(df_col)]
    ### annotation components
    mat_col_fun = circlize::colorRamp2(c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), c("#253494","#2c7fb8","#41b6c4", "#7fcdbb", "#c7e9b4", "#ffffcc"))
    genus_text_col = ifelse(df_row>0, "#fc8d62", "#66c2a5")
    
    column_ha = HeatmapAnnotation(df = df_col %>% select(Year, Age_grp2), 
                                  col = list(Year = c("2015" = "#bcbddc" , "2016" = "#756bb1"), 
                                             Age_grp2 = c("Age_0-3" = "#f1eef6", "Age_3-8" = "#bdc9e1","Age_8-18" = "#74a9cf", "Adults" = "#0570b0")), 
                                  simple_anno_size = unit(3, "mm"), 
                                  annotation_label = c("Year", "Age"), 
                                  annotation_name_gp = gpar(fontsize = 7,fontface = "bold"), 
                                  annotation_name_side = "left", 
                                  annotation_legend_param = list(Year = list(labels_gp = gpar(fontsize = 7), 
                                                                              title_gp = gpar(fontsize = 8, fontface = "bold")), 
                                                                 Age_grp2 = list(labels_gp = gpar(fontsize = 7), 
                                                                                 title_gp = gpar(fontsize = 8, fontface = "bold"))))
    
    row_ha = rowAnnotation(foo = anno_text(df_row$Sign, location = 0, rot = 0, just = "left"), 
                           gp = gpar(col = "black", lwd = 0.3), 
                           annotation_name_gp = gpar(fontsize = 7), 
                           annotation_name_side = "top")

    p <- Heatmap(mat_dat, 
                 col = mat_col_fun, 
                 name = "Relative Abundance", 
                 heatmap_legend_param = list(at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), 
                                             labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"), 
                                             labels_gp = gpar(fontsize = 7), 
                                             title_gp = gpar(fontsize = 8, fontface = "bold")),
                 cluster_columns = F, show_column_names = F,
                 column_order = rownames(df_col),
                 column_title_gp = gpar(fontsize = 7, fontface = "bold"),
                 column_split = df_col$Year,
                 #row_names_gp = gpar(col = genus_text_col, fontsize = 7),
                 row_names_gp = gpar(fontsize = 8), 
                 row_labels = df_row_name_label[rownames(df_row)],
                 row_dend_width = unit(15, "mm"),
                 row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
                 top_annotation = column_ha,
                 right_annotation = row_ha,
                 height = unit(8, "mm")*dim(mat_dat)[1],
                 width = unit(0.8, "mm")*dim(mat_dat)[2], 
    )
    p1 <- draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
    pdf(file = paste0("output/figures/Ancom_heatmap_sig_log_rel_ab_year_", BB, "_pvalue_filtered.pdf"), width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4, useDingbats = F)
    draw(p1)
    dev.off()
    
    p_genus_order = rownames(df_row)[row_order(draw(p))]
    p1_dat <- data.frame(Taxa = p_genus_order, stringsAsFactors = F) %>% separate(Taxa, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus"), sep = "\\.D_\\d_", remove = F) %>% mutate(Domain = gsub(x = Domain, pattern = "D_0_", replacement = ""))
    p1_dat$LR <- df_row$LR
    p1_dat$Flag <- p1_dat$LR>0
    p1_dat$No = rownames(p1_dat)
    p1_dat$BodySite = BB
    p1_dat$Year = YY
    write.table(p1_dat, file = paste0("output/figures/Ancom_sig_log_rel_ab_year_", BB, "_genera.txt"), sep = "\t", row.names = F, quote = F)
}
```


## compare blasto
```{r}
load("output/Mapping_Blasto.RData")
Mapping_Blasto = bdat_sample %>% mutate(Age_grp3 = str_replace(Age_grp2, " ", "_")) %>% 
  mutate(Age_grp2 = factor(Age_grp3, levels = c("Age_0-3", "Age_3-8", "Age_8-18", "Adults"), ordered = T))


BodySites <- c("Feces", "Mouth", "Nose", "Right_Arm", "Right_Hand")

Ancom_mf_blasto <- Mapping_Blasto %>% filter(SampleGroup=="Villagers", Body_Site %in% BodySites) %>% group_by(Body_Site) %>% group_split()

Ancom_rsl_blasto <- parallel::mclapply(Ancom_mf_blasto, function(x){
    list(x[1, "Body_Site"], ancom_wrap(ft_glom$Genus %>% select(Taxa, any_of(x$SampleID)), x, adjusted = T, main.var = "Blasto", adj.formula = "Urban+Gender+Age_grp2", repeat.var = NULL, longitudinal = F, random.formula = NULL, multcorr = 2, sig = 0.05, prev.cut = 1))
    }, mc.cores = 2)

save(Ancom_rsl_blasto, file = "output/Ancom_rsl_blasto_g.Rdata")
load("output/Ancom_rsl_blasto_g.Rdata")
```

### data prep
```{r}
Ancom_rsl_blasto_tbl <- lapply(Ancom_rsl_blasto, function(x){x[[2]]$W.taxa %>% mutate(Body_Site = as.character(x[[1]][1]))}) %>% do.call("rbind", .) %>% 
  filter(!grepl(pattern = "D_1_\\.D", otu.names))

BodySites <- c("Feces", "Mouth", "Nose", "Right_Arm", "Right_Hand")

while(F){
  sig_cutoff <- integer()
  for (BB in BodySites){
      # BB = "Feces"
      ## metadata
      Mf <- Mapping_Blasto %>% filter(Body_Site==BB, SampleGroup=="Villagers")
      ## Ancom results and catogrize the species according to W/effect size
      AR <- Ancom_rsl_blasto_tbl %>% filter(Body_Site==BB) %>% mutate(otu.names = as.character(otu.names)) %>% arrange(desc(W_stat))
      ### check the distribution of W-stats, 
      p <- ggplot(AR, aes(x = W_stat)) +
        geom_histogram(aes(y = ..density..), bins = 20) +
        geom_density() +
        geom_vline(xintercept = nrow(AR)*seq(0.6, 0.9, 0.1)) + 
        theme_bw() +
        labs(title = BB)
      print(p)
      
      table(AR$ES)
      #sig_cutoff[BB] <- readline(prompt = "Above which cut off deemed as significant? LT0.6(1), LT0.7(2), LT0.8(3), LT0.9(4)")
  }
}

sig_cutoff = c(1, 1, 1, 1, 1)
names(sig_cutoff) = c("Feces", "Mouth", "Nose", "Right_Arm", "Right_Hand")

fts_mt <- parallel::mclapply(BodySites, function(x){
    list(Mf = Mapping_Blasto %>% filter(Body_Site==x, SampleGroup=="Villagers"),
         AR = Ancom_rsl_blasto_tbl %>% filter(Body_Site==x) %>% mutate(otu.names = as.character(otu.names)) %>% arrange(desc(W_stat)))},
    mc.cores = nc)

fts <- parallel::mclapply(fts_mt, function(x){ft_glom$Genus %>% 
    select(Taxa:Genus, any_of(x$Mf$SampleID)) %>% 
    mutate(Taxa = make.names(Taxa)) %>%
    filter(Taxa %in% x$AR$otu.names)}, mc.cores = nc)

lrs_b_grp <- list()
for (ss in seq_along(fts)){
    ft_t <- fts[[ss]]
    Mf <- fts_mt[[ss]][["Mf"]] %>% filter(SampleID %in% colnames(ft_t))
    YY = Mf$Year[1]
    BB = Mf$Body_Site[1]

    ft_t_rel_ab <- ft_t %>% mutate(across(starts_with("X"), ~ .x/10000))

    ft_t_rel_ab_log10 <- ft_t_rel_ab %>% mutate(across(starts_with("X"), ~ ifelse(.x == 0, log10(0.0001), log10(.x))))

    #lr_b_grp <- split(ft_t_rel_ab_log10, ft_t_rel_ab_log10$Taxa) %>% lapply(., function(x){10^((t(x[, -1]) %>% merge(., Mf, by.x = 0, by.y = 1) %>% lm(V1 ~ Blasto + Urban + Age_grp2 + Gender, data = .))$coefficient[2]) %>% log2() }) %>% unlist(use.names = T)
    #names(lr_b_grp) <- names(lr_b_grp) %>% gsub(pattern = "\\.BlastoPositive", replacement = "", x = .)
    #lrs_b_grp[[ss]] <- lr_b_grp
    
    coef_p_l = split(ft_t_rel_ab_log10, ft_t_rel_ab_log10$Taxa) %>% lapply(., function(x){coefd = (t(x[, -1]) %>% 
                                                                                      merge(., Mf, by.x = 0, by.y = 1) %>% 
                                                                                      lm(V1 ~ Blasto + Urban + Age_grp2 + Gender, data = .) %>% 
                                                                                      summary())$coefficients
                                                                              coefd[which(str_detect(rownames(coefd), "Blasto")),c("Estimate", "Pr(>|t|)")]
                                                                              })
    coef_and_p = do.call(rbind.data.frame, coef_p_l)
    names(coef_and_p) = c("coef","pvalue")
    rownames(coef_and_p) = names(coef_p_l)
    coef_and_p$padj = p.adjust(coef_and_p$pvalue, method = "BH")
    coef_and_p$LR = log2(10^coef_and_p$coef)
    lrs_b_grp[[ss]] <- coef_and_p
}
```

### heatmap
```{r}
for (ss in c(1,2,3,4,5)){

    ft_t <- fts[[ss]]
    Mf <- fts_mt[[ss]][["Mf"]] %>% filter(SampleID %in% colnames(ft_t))
    YY = Mf$Year[1]
    BB = Mf$Body_Site[1]
    lr_b_grp = lrs_b_grp[[ss]]
    AR_g <- fts_mt[[ss]]$AR
    # defining taxa that changed and unchanged based on sig_cutoff
    ind = BB
    ES_cutoff <- paste0("detected_",seq(0.6, 0.9, 0.1)[sig_cutoff[ind]])
    # relative abundance
    ft_t_rel_ab <- ft_t %>% mutate(across(starts_with("X"), ~ .x/10000))
    # rel abundance in log scale
    ft_t_rel_ab_log10 <- ft_t_rel_ab %>% mutate(across(starts_with("X"), ~ ifelse(.x == 0, log10(0.0001), log10(.x))))
    # heatmap of significantly changed features
    ## dataframe for the column annotation
    df_col <- Mf %>% select(SampleID, Age_grp2, Blasto) %>% arrange(Blasto,Age_grp2) %>% column_to_rownames(var = "SampleID")
    ## dataframe for the row(taxa) annotation, only significantly modified genera included
  taxa_stat = merge(lr_b_grp, AR_g, by.x = 0, by.y = 1)
    df_row = taxa_stat[which(taxa_stat[,ES_cutoff]==TRUE),]
    df_row = df_row %>% filter(!str_detect(Row.names, pattern = "Mitochondria|Chloroplast"), padj < 0.1) %>% 
      mutate(Sign = case_when(LR <= -2 ~ "--",
                              LR < 0 ~ "-",
                              LR == 0 ~ "",
                              LR < 2 ~ "+",
                              LR >= 2 ~ "++"),
             LR_abs = abs(LR)) %>% column_to_rownames("Row.names")
    if(nrow(df_row) > 40){df_row = df_row %>% arrange(desc(LR_abs)) %>% top_n(n = 40, wt = LR_abs)}
    if(nrow(df_row)<1){next}
    df_row_name_label = structure(gsub("D_\\d_", "", rownames(df_row)), names = rownames(df_row))
    df_row_name_label = structure(gsub("D_\\d_", "", rownames(df_row)), names = rownames(df_row))
    ## this is used to create the legend
    LR_sig_range <- df_row$LR %>% range
    ## data matrix for the heatmap
    mat_dat <- ft_t_rel_ab_log10 %>% select(Taxa, starts_with("X")) %>% column_to_rownames(var = "Taxa") %>% as.matrix %>% .[rownames(df_row), rownames(df_col)]
    ### annotation components
    mat_col_fun = circlize::colorRamp2(c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), c("#253494","#2c7fb8","#41b6c4", "#7fcdbb", "#c7e9b4", "#ffffcc"))
    genus_text_col = ifelse(df_row>0, "#fc8d62", "#66c2a5")
    
    column_ha = HeatmapAnnotation(df = df_col %>% select(Blasto, Age_grp2), 
                                  col = list(Blasto = Blasto_color, 
                                             Age_grp2 = c("Age_0-3" = "#f1eef6", "Age_3-8" = "#bdc9e1","Age_8-18" = "#74a9cf", "Adults" = "#0570b0")), 
                                  simple_anno_size = unit(3, "mm"), 
                                  annotation_label = c("Blasto status", "Age"), 
                                  annotation_name_gp = gpar(fontsize = 7,fontface = "bold"), 
                                  annotation_name_side = "left", 
                                  annotation_legend_param = list(Blasto = list(labels_gp = gpar(fontsize = 7), 
                                                                              title_gp = gpar(fontsize = 8, fontface = "bold")), 
                                                                 Age_grp2 = list(labels_gp = gpar(fontsize = 7), 
                                                                                 title_gp = gpar(fontsize = 8, fontface = "bold"))))
    
    row_ha = rowAnnotation(foo = anno_text(df_row$Sign, location = 0, rot = 0, just = "left"), 
                           gp = gpar(col = "black", lwd = 0.3), 
                           annotation_name_gp = gpar(fontsize = 7), 
                           annotation_name_side = "top")

    p <- Heatmap(mat_dat, 
                 col = mat_col_fun, 
                 name = "Relative Abundance", 
                 heatmap_legend_param = list(at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), 
                                             labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"), 
                                             labels_gp = gpar(fontsize = 7), 
                                             title_gp = gpar(fontsize = 8, fontface = "bold")),
                 cluster_columns = F, show_column_names = F,
                 column_order = rownames(df_col),
                 column_title_gp = gpar(fontsize = 7, fontface = "bold"),
                 column_split = df_col$Blasto,
                 #row_names_gp = gpar(col = genus_text_col, fontsize = 7),
                 row_names_gp = gpar(fontsize = 8), 
                 row_labels = df_row_name_label[rownames(df_row)],
                 row_dend_width = unit(15, "mm"),
                 row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
                 top_annotation = column_ha,
                 right_annotation = row_ha,
                 height = unit(8, "mm")*dim(mat_dat)[1],
                 width = unit(0.8, "mm")*dim(mat_dat)[2], 
    )
    p1 <- draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
    pdf(file = paste0("output/figures/Ancom_heatmap_sig_log_rel_ab_Blasto_", BB, "_pvalue_filtered.pdf"), width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4, useDingbats = F)
    draw(p1)
    dev.off()
    
    p_genus_order = rownames(df_row)[row_order(draw(p))]
    p1_dat <- data.frame(Taxa = p_genus_order, stringsAsFactors = F) %>% separate(Taxa, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus"), sep = "\\.D_\\d_", remove = F) %>% mutate(Domain = gsub(x = Domain, pattern = "D_0_", replacement = ""))
    p1_dat$LR <- df_row$LR
    p1_dat$Flag <- p1_dat$LR>0
    p1_dat$No = rownames(p1_dat)
    p1_dat$BodySite = BB
    p1_dat$Year = YY
    write.table(p1_dat, file = paste0("output/figures/Ancom_sig_log_rel_ab_Blasto_", BB, "_genera.txt"), sep = "\t", row.names = F, quote = F)
}
```




