---
title: "VFA 2016"
author: "HS"
date: "9/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## library   
```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

## load and process data
```{r}
Mapping_VFA = read.table("Bolivar-2016-VFA-Metadata-20190327-jw.txt",sep = "\t",header = T, stringsAsFactors = F)
# Acetate:Valerate - umol/g feces, feces weight - mg

Mapping_VFA = Mapping_VFA %>% 
  rename(feces_weight = Weight..mg.) %>%
  mutate(Expo = ifelse(Village=="Kanarakuni", "Medium", "Low") %>% factor(levels = c("Low", "Medium")),
         Age_num = as.numeric(Age), 
         Age_grp1 = ifelse(Age_num>=18, "Adults", "Children"), 
         Age_grp2 = case_when(Age_num<=3 ~ "Age 0-3", 
                              Age_num<=8 ~ "Age 3-8",
                              Age_num<18 ~ "Age 8-18", 
                              Age_num>=18 ~ "Adults")) %>%
  mutate(Age_grp2 = factor(Age_grp2, levels =c("Age 0-3","Age 3-8","Age 8-18","Adults")),
         Age_grp1 = factor(Age_grp1, levels =c("Children","Adults"))) %>%
  mutate(Height = as.numeric(str_remove(Height, "_")),
         Glucose = as.numeric(str_remove(Glucose, "_mg/dl")),
         Uric_acid = as.numeric(str_remove(Uric_acid, "_mg/dl")),
         Cholesterol = as.numeric(str_remove(Cholesterol, "_mg/dl")),
         Hemoglobin = as.numeric(str_remove(Hemoglobin, "_g/dl")),
         Systolic = rowMeans(select(.,c(Systolic_1,Systolic_2,Systolic_3)), na.rm=T) %>% round(1),
         Diastolic = rowMeans(select(.,c(Diastolic_1,Diastolic_2,Diatolic_3)), na.rm=T%>% round(1))
  )

save(Mapping_VFA, file = "Mapping_VFA.rData")

```

## explore
```{r}
Expo_color <- c("#66c2a5", "#fc8d62")
names(Expo_color) <- c("Low", "Medium")

dat = Mapping_VFA %>% filter(!is.na(Acetate))
table(dat$Gender, dat$Expo)

my_summarize = function(x){
  data.frame(
             N = n(),
             N.nna = sum(!is.na(x)),
             Min = min(x,na.rm = T),
             Med = median(x, na.rm = T),
             Mean = mean(x, na.rm = T),
             Max = max(x,na.rm = T),
             SD = sd(x,na.rm = T)
             )
}

dat_summarize = function(var, dat){
  res = dat %>% group_by(Expo, Age_grp1, Gender) %>% summarise(my_summarize(get(var))) %>% 
    mutate(Var = var, mean_sd = str_c(round(Mean,1), " \u00b1 ", round(SD,1)), nonna_prop = str_c("(", N.nna,"/",N,")")) %>%
    select(Var, Expo, Age_grp1, Gender, mean_sd, nonna_prop) %>% 
    pivot_wider(names_from = c(Expo, Gender), 
              values_from =c(mean_sd, nonna_prop)) %>% ungroup()
  res
} 

a = lapply(c("Acetate","Propionate","Isobutyrate","Butyrate", "Isovalerate", "Valerate"), 
           function(x) dat_summarize(dat = dat, var = x))
res_VFA = do.call(rbind, a)

lmdat = dat %>% select(Acetate:Valerate,Age_num,Gender,Expo,BMI,Systolic,Diastolic)

fit = step(lm(BMI ~ ., data = lmdat))
summary(fit)

fit = lm(Systolic ~ ., data = lmdat)
summary(fit)

fit = lm(Diastolic ~ ., data = lmdat)
summary(fit)

a = lapply(c("Acetate","Propionate","Isobutyrate","Butyrate", "Isovalerate", "Valerate"), 
           function(v){sumfit = summary(lm(get(v) ~ Expo + Gender + Age_num, data = lmdat))
           res = sumfit$coefficients %>% as.data.frame() %>% rownames_to_column("Var") %>% mutate(Outcome = v)
           res})
res_lm_vfa_expo = do.call(rbind, a) %>% mutate(pvalue = round(`Pr(>|t|)`, 4))
```

## VFA vs Expo
```{r}
dat = Mapping_VFA %>% filter(!is.na(Acetate))

library(Hmisc)
library(agricolae)
kw_and_CI = function(wdat, x, y){
  wk = wdat %>% split(., .[x])
  out1 = sapply(wk, function(df){smean.cl.boot(df[y], conf.int = .95)}) %>% t() %>% as.data.frame() %>% rownames_to_column(var = x)
  ktest = kruskal(wdat[y], wdat[x], alpha = 0.05, p.adj="none", group=T, main = "wdat", console=FALSE)
  out2 = ktest$groups %>% rownames_to_column(var = x) %>% select(all_of(x), groups)
  out1 = out1 %>% left_join(out2, by = x )
  out1
}

res_expo_vfa_kw = data.frame(Expo=NA, Mean=NA, Lower=NA, Upper=NA, groups=NA, Var=NA)
for (v in c("Acetate","Propionate","Isobutyrate","Butyrate", "Isovalerate", "Valerate")){
  for(a in c("Children", "Adults")){
    res = kw_and_CI(wdat=dat %>% filter(Age_grp1 == a), x="Expo", y=v)
    res$Var = v
    res_expo_vfa_kw = rbind(res_expo_vfa_kw, res)
  }
}
res_expo_vfa_kw = res_expo_vfa_kw %>% filter(!is.na(Expo))

for (v in c("Acetate","Propionate","Isobutyrate","Butyrate", "Isovalerate", "Valerate")){
  g = ggplot(dat, aes(x = Age_grp1, y = get(v), color = Expo)) + 
    geom_boxplot() + 
    geom_point(position = position_jitterdodge()) + 
    scale_color_manual(values = Expo_color, aesthetics = c("colour", "fill"), name = "Exposure") + 
    labs(x="", y = paste0(v, " umol/g feces"))
  ggsave(filename = paste0("Expo_",v,"_by_age_grp1.png"), g, 
         height = 6, width = 8, units = "in", dpi = 300)
}

wdat = dat %>% select(Tube_ID,Expo, Age_grp1, Age_grp2, Acetate:Valerate) %>% 
  pivot_longer(cols = Acetate:Valerate, names_to = "VFA") %>% 
  mutate(VFA = factor(VFA, levels = c("Acetate","Propionate","Butyrate","Isobutyrate", "Valerate",  "Isovalerate"), ordered = T))
g = ggplot(wdat, aes(x = Age_grp1, y = value, color = Expo)) +
  geom_boxplot() + 
  geom_point(position = position_jitterdodge()) + 
  scale_color_manual(values = Expo_color, aesthetics = c("colour", "fill"), name = "Exposure") +
  labs(x="", y = expression(paste(mu, "mol/g feces"))) + 
  facet_wrap(VFA ~ ., ncol = 3)
ggsave(filename = paste0("All_VFA_by_age_grp1.png"), g, 
         height = 6, width = 8, units = "in", dpi = 300)

```










